server:
  port: 18080


# 配置应用名称(必须配置，否则Nacos注册失败)
spring:
  application:
    name: demo99-service
  
  # 配置OpenAI
  ai:
    openai:
      api-key: sk-ed72892d7a9f4c13b530db0fd6490f58
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medhelper?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    root: error
    org.springframework.ai.chat.client: DEBUG

